### ISSUE TITLE
[Feat] view 작업

### ISSUE THREAD

**Issue by yong313** [yong313/payhere_project_yong313#1]
### TODO
 - [x] 메인페이지 view 작업
 - [x] 모달 컴포넌트 작업
 - [x] api 호출 에러 핸들링
 - [x] 상세페이지 view 작업
 - [x] no issues view 작업
